version: '3.9'

services:
  proxy:
    container_name: todo_proxy
    image: traefik:v2.6
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .docker/proxy/static.yml:/etc/traefik/traefik.yml:ro
      - .docker/proxy/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      - proxy

networks:
  proxy:
    name: proxy